name: pre-commit

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  pre-commit:
    # pull requests are a duplicate of a branch push if within the same repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # v3.0.0
        with:
          extra_args: --all-files
